JARgorithm/Algorithm

.idea/misc.xml, .idea/vcs.xml, session1/bfs/chaeyeon/ShortestGameMap.java, session1/bfs/chaeyeon/WordConversion.java
➡️**알고리즘**
시작점에서 끝점까지의 모든 경로를 탐색하여 최단거리를 구해야하는 문제로 BFS 방식 사용
➡️**문제풀이**
- Queue를 활용해 BFS 탐색으로 구현
- (0,0)에서 시작하여 해당점에서 상하좌우, 이동 가능한 칸(maps[nx][ny] == 1)으로만 이동
- 이미 방문한 위치는 visited 배열로 체크하여 중복 탐색 방지 및 거리 누적 관리
- 도착 지점에 도달하면 해당 거리(current.distance)를 반환
</br>
➡️**알고리즘**
해당 문제는 모든 경로를 탐색하는 것이 아니라 begin == target이라는 조건을 만족하는 최단 거리를 찾는 문제이기에 BFS 알고리즘을 사
➡️**문제풀이**
- Queue를 활용해 BFS 탐색으로 구현
- Node 클래스를 활용하여 각 상태에서의 단어와 해당 단계까지의 변환 횟수인 Depth를 함께 저장함으로써, target에 도달한 시점에 바로 결과값 도출 가능!
- 문제 조건이 “한 번에 한 글자만 바꿀 수 있다”는 제약이 있으므로, canConvert 함수를 통해 두 단어 간 글자 차이가 정확히 1개인지를 판단하여 유효한 변환만 탐색
- BFS 탐색 중, 아직 방문하지 않았고 한 글자만 다른 단어를 발견하면 큐에 삽입하고 visited 배열을 통해 중복 방문 방지
- 모든 탐색이 끝날 때까지 target에 도달하지 못할 경우 변환이 불가능하므로 0을 반환
=> 게임 맵 최단거리 (프로그래머스 - 1844) & 단어변환 (프로그래머스 - 43163)

session1/bfs/gayeong/TargetNumber.java, session1/dfs/gayeong/TargetNumber.java, session1/session1.iml, session2/session2.iml, session3/session3.iml
모든 경우의 수를 다 확인해야 하는 문제이기 때문에 DFS를 사용했습니다.
1. 모든 수에 대해서 +, - 부호를 붙였을 때의 값을 구한다.
=> 타겟 넘버 문제 풀이

.idea/vcs.xml, session1/bfs/gayeong/ElectricityDivider.java, session1/bfs/gayeong/Network.java, session1/session1.iml
하나의 네트워크를 탐색하기 위해선 DFS, BFS 방법을 사용하여 탐색할 수 있습니다.
모든 정점을 순회하면서, 아직 방문되지 않은 노드를 발견하면
BFS 시작 → 하나의 네트워크 탐색
=> 네트워크 문제 풀이

session1/dfs/gayeong/Alphabets.java
1. DFS(깊이 우선 탐색) + 백트래킹을 사용해 모든 경로를 탐색
2. boolean[26] seen 배열로 현재 경로에서 사용한 알파벳 관리
3. depth 파라미터로 현재 이동 칸 수(경로 길이)를 추적, 전역 result에 최댓값 갱신
=> feat: 알파벳 문제 풀이

session1/dfs/chaeyeon/SafeArea.java
➡️**알고리즘**
DFS를 활용한 시뮬레이션 이용
➡️**문제풀이**
해당 문제에서 가장 중요한 부분은 **시뮬레이션**을 통해 가장 많은 안전지대를 확보할 수 있는 높이를 찾는 것이다.
- 입력된 지도의 모든 좌표를 탐색하면서, 지형의 최대 높이를 구한다. 
-  **비의 높이**를 0부터 최대 높이까지 변화시키며 **시뮬레이션을 반복**
- 매 높이별 시뮬레이션 결과 중 가장 많은 안전 영역 개수를 최종 결과로 출력!
=> 안전영역 (백준 - 2468)

session1/bfs/chaeyeon/AlgoSpot.java, session1/bfs/chaeyeon/Hide3.java, session1/bfs/chaeyeon/MakeMaze.java
➡️**알고리즘**
아래와 같이 **가중치가 존재**하기에  0-1 BFS 알고리즘 사용
- X * 2로 이동 → 0초 (가중치 0)
- X + 1, X - 1로 이동 → 1초 (가중치 1)
➡️**문제풀이**
- Deque를 사용해서 가중치를 아래와 같이 처리하여 최단 거리 이동 시간을 구함
1. 순간이동(0초) → offerFirst() 
2. 걷기(1초) → offerLast()
- K에 도달하면 time[K]이 최소시간이다!
</br>
➡️**알고리즘**
- 벽은 가중치 1, 빈방은 가중치 0으로 가중치가 존재하는 최단거리 문제이기에 BFS(0-1) 알고리즘으로 해당 문제에 접근
➡️**문제풀이**
- 현재 위치 (x, y)에서 인접한 (nx, ny)로 갈 수 있는지 확인
- cnt = map[nx][ny] → 벽이면 1, 아니면 0
- distance[nx][ny] > distance[x][y] + cnt이면 갱신
- 더 벽 부수기 횟수로 갈 수 있는 경로라면 업데이트
- cnt == 0이면 deque 앞에 삽입 → 먼저 탐색
- cnt == 1이면 deque 뒤에 삽입 → 나중에 탐색
이 과정을 통해 가장 적은 벽을 부수는 경로부터 탐색하므로, 최종적으로 dist[N-1][M-1]에는 최소 벽 부순 횟수가 저장되게 된다.
</br>
➡️ 알고스팟 (백준 - 1261) 문제와 알고리즘 선택 및 문제풀이가 동일‼️‼️
=> 숨바꼭질3 (백준 - 13549) & 알고스팟  (백준 - 1261) & 미로만들기 (백준 - 2665)

session1/bfs/gayeong/AlgoSpot.java
1. distance[x][y] : x, y까지 오는 데 부순 벽의 최소 개수
2. 이동 가능한 좌표이면 distance 변화 X
3. 막혀 있는 벽이면 distance + 1을 하여 우선순위큐에 삽입
=> 알고스팟 문제 풀이

session1/bellmanFord/chaeyeon/TimeMachine.java, session1/dijkstra/chaeyeon/Delivery.java
➡️**알고리즘**
- 최단거리 문제이며 A, B, C (1 ≤ A, B ≤ N, -10,000 ≤ C ≤ 10,000) 조건에서 C의 값이 음수일 수 있다는 점 때문에 다익스트라 알고리즘 대신 벨만포드 알고리즘을 사용했습니다.
➡️**문제풀이**
- 도시 수와 버스 노선 수, 간선 정보를 Edge 클래스를 이용해 저장
- 시작노드에서 각 노드까지의 최단 거리를 dist배열을 통해 저장
- 벨만포드 알고리즘을 적용하여 모든 간선을 반복하며 거리 갱신 수행
- N번째 반복에서도 거리 갱신이 발생한다면 음수 사이클이 존재한다고 판단하고 -1을 출력 후 종료
=> 타임머신 (백준 - 11657)

session1/dijkstra/chaeyeon/Delivery.java
➡️**알고리즘**
최단 거리를 기반으로 거리가 K 이하인 마을의 개수를 구하는 문제이므로 다익스트라 알고리즘을 사용하여 각 노드까지의 최단 거리를 계산
➡️**문제풀이**
- 마을과 도로 정보를 기반으로 양방향 인접 리스트 형태로 그래프 생성
- 각 마을까지의 최단 거리를 무한대로 초기화 (-> dist)
- 우선순위 큐를 활용한 다익스트라 알고리즘 수행
- dist에 저장된 값을 기반으로 거리가 K이하인 마을의 개수 도출
=> 배달 (프로그래머스 - 12978)

session1/bellmanFord/chaeyeon/TimeMachine.java, session1/bellmanFord/chaeyeon/WormHole.java, session1/dijkstra/chaeyeon/Delivery.java, session1/dijkstra/chaeyeon/SharedTaxiFare.java
➡️**알고리즘**
- 도착을 하게 되면 시작을 하였을 때보다 시간이 뒤로 가게 된다. 
- 시간이 뒤로 간다라는 말은 음수 간선이 존재한다는 것을 의미하기에 벨만포드 알고리즘 사용
➡️**문제이해**
- **도로** (일반 간선)
- 마을 ↔ 마을 (양방향)
- 시간은 **양수**
- **웜홀** (시간을 되돌리는 장치)
- 마을 → 마을 (단방향)
- 시간은 **음수**
> 이 나라에 **시간을 되돌아올 수 있는 사이클(=음수 사이클)**이 존재하는지 알아내야 한다.
> 
> 
> 즉, **출발해서 돌아왔는데 시간이 감소한 경우가 있는지** 확인하는 게 문제
>
🚨 **주의사항**
- bellmanFord() 함수에서 dist 거 배열을 0으로 초기화 
- > 이렇게 하는 이유는 문제상 "모든 노드에서 출발하는 음수 사이클도 찾아야" 하므로 특정 노드에만 거리 0을 주지 않고, 모든 노드의 거리를 0으로 초기화해야만 한다!!
=> 웜홀  (백준 - 1865)

session1/bellmanFord/chaeyeon/TimeMachine.java, session1/dijkstra/chaeyeon/Delivery.java, session1/dijkstra/chaeyeon/SharedTaxiFare.java
➡️**알고리즘**
- 최단 거리를 구하는 문제이며 음수 간선이 없기 때문에 다익스트라 알고리즘 사용‼️
➡️**문제풀이**
- 다익스트라는 **1개의 출발지**에서 모든 지점까지의 최소비용을 구하는 알고리즘으로 해당 문제는 총 3번의 다익스트라를 진행
1. 합승지점까지 모든 지점까지의 최소 비용 → distS
2. A지점까지 모든 지점까지의 최소 비용 → distA
3. B지점까지 모든 지점까지의 최소 비용 → distB
- 만약 합승을 안할 경우 출발하자마자 각자 따로 이동하기에 1의 값이 0이 되므로 합승하지 않을 경우의 최단거리도 구해진다.
=> 합승 택시 요금  (프로그래머스 - 72413)

session1/bellmanFord/gayeong/Wormhole.java
문제에서 "출발했을 때보다 시간이 되돌아가 있는 경우가 있는지"를 묻고 있으므로, 이는 음수 사이클의 존재 여부를 판단하는 문제입니다.
따라서, 이를 탐지할 수 있는 벨만-포드 알고리즘을 사용했습니다.
이 문제는 특정 시작 정점이 주어지지 않습니다. ( 한 지점에서 출발을 하여서 시간여행을 하기 시작하여 다시 출발을 하였던 위치로 돌아왔을 때라고 문제에 명시되어 있다.)
처음에는 distance[1] = 0처럼 정점 1을 시작 정점으로 설정해도 통과가 가능했지만, 이는 문제 데이터가 운 좋게 그렇게 구성되어 있었기 때문입니다.
⚠️ **반례 예시**
그러나 아래의 경우 시작 정점을 1로 했을 땐 음수 사이클을 탐지할 수 없습니다.
(1)---(2)
(3)→(4)→(5)→(3)   ← 음수 사이클
정점 1과 3~5번 사이클은 서로 연결되어 있지 않음
따라서 distance[3], distance[4], distance[5]는 초기값 INF에서 갱신되지 않으며,
결과적으로 음수 사이클이 존재함에도 탐지가 불가능
가상의 정점 0번을 추가하고
모든 정점(1 ~ N)에 비용이 0인 간선을 연결합니다.
이는 모든 정점을 시작 정점으로 삼기 때문에 어느 정점에서든지 음수 사이클을 발견할 수 있습니다.
=> feat: 웜홀 문제 풀이

session1/dijkstra/chaeyeon/FurthestNode.java
➡️**알고리즘**
- 가장 멀리 떨어진 노드란 최단경로로 이동했을 때 간선의 개수가 가장 많은 노드들을 의미
- 모든 간선의 가중치가 1로 동일하고 음의 간선이 없으므로, 다익스트라 알고리즘을 사용하여 최단 거리를 구한다.
➡️**문제풀이**
- 우선순위 큐를 활용하여 노드 1번으로부터의 최단 거리를 구한다.
- 거리 배열은 distance[]로 관리하며, 초기값은 Integer.MAX_VALUE, 1번 노드의 거리는 0으로 설정
- 모든 간선 가중치가 1이므로, 현재 노드까지 거리 + 1로 인접 노드의 최단 거리를 갱신
- 최단 거리 배열에서 가장 큰 값을 찾아, 이것이 1번 노드에서 가장 멀리 떨어진 거리임을 확인
=> 가장 먼 노드  (프로그래머스 - 49189)

session1/bellmanFord/chaeyeon/Worries.java, session1/dijkstra/chaeyeon/FurthestNode.java
➡️**알고리즘**
- 벨만-포드알고리즘을 사용하여 최단 경로가 아닌 **최대 이익 경로를 계산**
- 이 문제는 비용이 있는 간선과 도시 방문 시마다 얻는 수익이 동시에 주어지므로, 실제로는 "수익 - 비용"을 누적하며 이익을 최대화하는 구조
- 사이클로부터 도착 도시에 도달 가능한지 여부를 판단하기 위해 BFS를 사용
-> 최대 이익 경로를 계산 시 손해로 마이너스가 날 수 있기에 벨만포드 알고리즘 사용!
➡️**문제풀이**
-dist[] 배열을 사용하여 각 노드까지 도달했을 때의 최대 수익을 저장
- 초기에는 모든 도시의 수익을 Long.MIN_VALUE로 설정하고, 출발 도시의 수익만 초기화
- 벨만-포드 알고리즘을 N-1번 반복하여 모든 도시까지의 최대 수익을 갱신
- 이후 N번째 반복에서 수익이 추가로 갱신되는 간선이 존재한다면, 양의 사이클이 존재할 가능성이 있으므로 해당 도시에서 도착 도시에 도달할 수 있는지를 BFS로 확인
1. 도달 가능하다면 → Gee 출력
2. 불가능하다면 → 정상 종료
3. 도착 도시에 도달할 수 없다면 gg,
4. 양의 사이클이 없다면 도착 도시의 최대 수익을 출력
=> 오민식의 고민 (백준 - 1219)

session1/backtracking/chaeyeon/Dictionary.java
➡️**알고리즘**
DFS + 백트래킹을 사용
➡️**문제풀이**
- 빈 문자열부터 시작하여, 모음을 하나씩 붙여 나가는 방식으로 단어를 생성
- 각 단어를 생성할 때마다 cnt를 증가시키며, 목표 단어와 일치하는 경우 해당 cnt 반환
- 단어 길이가 5를 초과하는 경우 더 이상 탐색하지 않도록 백트래킹 조건을 추가해 가지치기를 수행
=> 모음사전 (프로그래머스 - 84512)

session1/backtracking/chaeyeon/Dictionary.java, session1/backtracking/chaeyeon/FindPrime.java
➡️**알고리즘**
DFS + 백트래킹 알고리즘 활용
➡️**문제풀이**
- 주어진 문자열의 숫자들을 이용해 만들 수 있는 모든 순열 조합을 DFS와 백트래킹을 통해 탐색
- 숫자를 조합할 때마다 Set 자료구조를 이용해 중복 제거
- 조합된 문자열이 비어있지 않다면 숫자로 변환 후 Set에 저장
- 모든 조합을 완료한 후, Set에 저장된 수들 중 소수인지 판별하여 개수 카운트
=> 소수 찾기 (프로그래머스 - 42839)

session1/src/week3/backtracking/gayeong/ChickenDelivery.java
최대 13개의 치킨집 중에서 M개를 선택 -> 조합 -> dfs + 백트래킹
1. 집(1)과 치킨집(2)의 좌표를 각각 저장
2. 치킨집 조합 생성 (DFS + 백트래킹)
3. 선택된 M개의 치킨집 조합에 대해 도시의 치킨 거리를 계산
4. 모든 집에 대해 현재 선택된 치킨집 조합과의 거리 중 최솟값을 구한 후, 총합을 계산
5. 계산된 값을 기존의 최소 치킨 거리와 비교하여 최솟값을 갱신합니다.
=> 치킨 배달 문제 풀이

session1/backtracking/chaeyeon/FindPrime.java, session1/src/week3/backtracking/chaeyeon/NQueen.java
➡️**알고리즘**
모든 가능한 경우의 수를 구하는 문제로 DFS+백트래킹 사용
➡️**문제풀이**
- 같은 행에는 퀸을 하나만 놓을 수 있으므로, 행을 하나씩 이동하면서 가능한 열에 퀸을 놓는다.
- 퀸은 **세로(열)**, **왼쪽 대각선**, **오른쪽 대각선**으로 공격할 수 있으므로, 이 3가지를 체크하면서 백트래킹
1. column[c]: 열 c에 퀸이 있는지 여부
2. diag1[row + c]: ↘ 방향 대각선 체크용 배열
3. diag2[row - c + n - 1]: ↙ 방향 대각선 체크용 배열
=> N-Queen (백준 - 9663)

session1/backtracking/chaeyeon/FindPrime.java, session1/src/week3/backtracking/chaeyeon/DeliverChicken.java, session1/src/week3/backtracking/chaeyeon/LetCard.java, session1/src/week3/backtracking/chaeyeon/NQueen.java, session3/session3.iml
➡️**알고리즘**
DFS+백트래킹 사용
➡️**문제풀이**
- 카드는 한 번만 사용할 수 있으며, 선택한 순서에 따라 만들어지는 숫자가 달라지므로 순열을 고려
- DFS를 통해 가능한 모든 카드 조합을 생성하고, depth == k일 때 현재까지 만든 문자열 current를 결과 집합에 추가
- Set을 사용함으로써 중복된 숫자 생성을 방지하고, 최종적으로 서로 다른 정수의 개수를 계산
=> 카드놓기 (백준 - 5568)

session1/src/week3/backtracking/gayeong/Password.java
주어진 알파벳으로 조건을 만족하는 암호를 구하는 문제이므로 DFS + 백트래킹을 사용하였습니다.
dfs(start, depth, pwd, vowelCnt, consCnt)
- start: 다음에 탐색할 인덱스
- depth: 현재까지 선택한 알파벳 수
- pwd: 현재까지 만든 암호 문자열
- vowelCnt, consCnt: 모음, 자음 개수 카운트
=> 암호만들기 문제 풀이

session1/backtracking/chaeyeon/FindPrime.java, session1/src/week3/backtracking/chaeyeon/DeliverChicken.java, session1/src/week3/backtracking/chaeyeon/NQueen.java, session1/src/week3/backtracking/chaeyeon/PartialSequence.java, session1/src/week3/backtracking/chaeyeon/Sudoku.java, session1/src/week3/backtracking/chaeyeon/WordMath.java, session1/src/week4/chaeyeon/Maze.java
➡️**알고리즘**
"검은 방을 흰 방으로 바꾸는 최소 횟수"를 구하는 시뮬레이션 문제로 방을 바꾸는 행위를 하나의 **"가중치가 있는 이동"** 으로 해석할 수 있기에 가중치가 0 또는 1인 상황에 적합한 0-1 BFS 알고리즘을 사
➡️**문제풀이**
- 흰 방은 그냥 이동할 수 있는 경로로 비용이 들지 않고 검은 방은 흰 방으로 바꿔야 이동 가능하기에 비용+1 발생
- 출발점 (0,0)에서 도착점 (n-1,n-1)까지 이동하면서 검은 방을 최소한으로 지나도록 시뮬레이션을 수행
- Deque를 활용하여, 흰 방은 덱 앞에 넣어 먼저 탐색되도록, 검은 방은 덱 뒤에 넣어 나중에 탐색 → 자연스럽게 최소 비용 경로가 먼저 처리됨
- 도착점에 가장 먼저 도달했을 때의 cost가 정답
=> 미로 만들기 (백준 - 2665)

session1/src/week4/simulation/gayeong/Ball.java
1. i, j, k 를 M번 입력받는다.
2. 입력받을 때마다 i부터 j까지 버킷을 k로 채운다.
3. bucket을 출력한다.
=> 공 넣기 문제 풀이

session1/src/week4/chaeyeon/Cheese.java, session1/src/week4/chaeyeon/RainDrop.java
**📌 핵심 아이디어**
각 칸 기준으로 좌우에 있는 가장 높은 블록을 기준으로 물이 고일 수 있는지를 판단하는 것
**➡️문제풀이**
- 입력으로 주어진 높이 배열에서 i번째 블록을 기준으로 좌우를 탐색
- i번째 블록에 물이 고이기 위해서는 왼쪽에 있는 블록들 중에서 가장 높은 값, 오른쪽에 있는 블록들 중에서 가장 높은 값 이 두 값 중 더 작은 값이 i 위치에서 고일 수 있는 최대 높이가 된다.
- 이 최대 높이에서 현재 블록의 높이를 뺀 값이 i에 고일 수 있는 빗물의 양이 된다.
=> 빗물 (백준 - 14719)

session1/src/week4/chaeyeon/Cheese.java
➡️**알고리즘**
BFS를 활용하여 외부 공기 영역을 탐색
➡️**문제풀이**
- 매 반복마다 외부 공기 영역을 -1로 표시하여 치즈와 내부 공기를 구분
- 전체 맵을 순회하며 치즈 중에서 외부 공기와 2변 이상 접촉하는 칸을 찾아 녹일 리스트에 추가
- 녹일 치즈가 없으면 반복을 종료, 그렇지 않으면 리스트에 있는 치즈를 0으로 바꾸어 녹인다.
=> 치즈 (백준 - 2638)

session1/src/week3/backtracking/chaeyeon/Election.java
➡️**문제풀이**
- 후보가 1명일 경우 매수할 필요가 없으므로 바로 0출력
- 가장 많은 표를 가진 후보를 찾아 표를 매수하고 다솜이게 주는 과정을 반복
`votes[maxIndex]--;`
`votes[0]++;`
=> 국회의원 선거 (백준 - 1417)

session1/src/week3/backtracking/chaeyeon/Election.java, session1/src/week3/backtracking/chaeyeon/Fire.java
➡️**알고리즘**
BFS  + 시뮬레이션
➡️**문제풀이**
- 불과 사람의 초기 위치를 각각 별도의 큐에 넣는다.
- BFS를 반복하며 시간 단위로 불부터 먼저 확산시킨다.
- 이어서 사람을 이동시키는데, 만약 사람이 건물 밖으로 나갈 수 있으면 탈출 성공으로 현재 시간+1을 반환한다.
- 사람이 더 이상 움직일 곳이 없으면 탈출 불가능으로 판단
=> 불 (백준 - 5427)

session1/src/week4/simulation/gayeong/Vote.java
1. 다솜이의 득표수를 제외한 득표수는 우선순위큐에 넣어 오름차순으로 정렬한다.
2. 가장 큰 득표수를 큐에서 꺼내어 다솜이의 득표수보다 크거나 같은 경우 한 표를 다솜이에게 넘긴 후 큐에 삽입한다.
3. 다솜이의 득표수가 다른 사람의 득표수보다 커질 때까지 위의 과정을 반복한다.
=> 국회의원 선거 문제 풀이

session1/src/week4/simulation/chaeyeon/Cheese.java, session1/src/week4/simulation/chaeyeon/Escape.java, session1/src/week4/simulation/chaeyeon/Maze.java, session1/src/week4/simulation/chaeyeon/RainDrop.java, session1/src/week4/simulation/chaeyeon/TurnArray.java, session1/src/week4/simulation/chaeyeon/putBall.java, session1/src/week5/chaeyeon/ExpressionN.java
➡️**알고리즘**
동적 계획법과 집합을 활용
➡️**문제풀이**
- dp[i]는 숫자 N을 i번 사용해서 만들 수 있는 수들의 집합(Set<Integer>)을 저장
- DP 점화식 구성
- i번 사용했을 때 만들 수 있는 수는, j번과 (i-j)번을 나누어 조합할 수 있는 수들의 사칙연산 결과로 구할 수 있다.
- 사칙연산 시 주의할 점) 나눗셈은 b != 0일 때만 수행
=> N으로 표현 (프로그래머스 - 42895)

session1/src/week4/simulation/chaeyeon/Cheese.java, session1/src/week4/simulation/chaeyeon/Escape.java, session1/src/week4/simulation/chaeyeon/Maze.java, session1/src/week4/simulation/chaeyeon/RainDrop.java, session1/src/week4/simulation/chaeyeon/TurnArray.java, session1/src/week4/simulation/chaeyeon/putBall.java, session1/src/week5/chaeyeon/ExpressionN.java, session1/src/week5/chaeyeon/IntegerTriangle.java
➡️**알고리즘**
동적 계획법
➡️**문제풀이**
- 해당 문제는 Bottom-up 방식을 활용
- `triangle[i][j] += Math.max(triangle[i+1][j], triangle[i+1][j+1])` 을 이용해서 최댓값을선택하면서 위로 올라간다.
- 결론적으로 삼각형 맨 꼭대기인 triangle[0][0]에 가장 큰 누적 합이 저장되게 된다.
=> 정수 삼각형 (프로그래머스 - 43105)

session1/src/week5/chaeyeon/GoSchool.java, session1/src/week5/chaeyeon/Operations.java
➡️**알고리즘**
Bottom-Up 방식의 동적 계획법 사용
➡️**문제풀이**
- 시작점 (1,1)은 경로 수가 1개이므로 dp[1][1] = 1로 초기화
- puddles 배열을 순회하며 물웅덩이 좌표를 dp[y][x] = -1로 체크
- 이중 for문으로 dp 배열을 채워나감
- 현재 위치가 물웅덩이이면 경로 수를 0으로 설정
- 그렇지 않다면, 왼쪽(dp[i][j-1])과 위쪽(dp[i-1][j])에서 오는 경로 수의 합을 저장
- 경로 수가 커질 수 있으므로 중간 계산마다 1,000,000,007로 나눈 나머지를 저장
=> 등굣길 (프로그래머스 - 42898)

session1/src/week5/chaeyeon/dp/gayeong/Triangle.java
1. 위에서 아래로 탐색한다.
2. 해당 위치에서 고를 수 있는 선택지는 대각선 왼쪽 위, 대각선 오른쪽 위 두 가지이다.
3. 두 숫자 중 큰 숫자를 골라 현재 위치의 값을 최댓값으로 갱신한다.
4. 그래프의 맨 마지막 행의 원소 중 가장 큰 값을 찾아 출력한다.
=> 정수 삼각형 문제 풀이

.idea/uiDesigner.xml, session1/src/week5/chaeyeon/BuyCard.java, session1/src/week5/chaeyeon/Change.java, session1/src/week5/chaeyeon/DeliverSugar.java, session1/src/week5/chaeyeon/Thief.java, session1/src/week5/chaeyeon/TreeAndQuery.java, session1/src/week5/chaeyeon/WithTaxiFare.java, session1/src/week6/joochaeyeon/Camera.java, session1/src/week6/joochaeyeon/ConnectLand.java, session1/src/week6/joochaeyeon/JoyStick.java, session1/src/week6/joochaeyeon/LifeBoat.java, session1/src/week6/joochaeyeon/MakeBigNum.java, session1/src/week6/joochaeyeon/WorkoutClothes.java, session2/week1/chaeyeon/Virus.java
➡️**알고리즘**
너비우선 탐색 사용
➡️**문제풀이**
- 1번 컴퓨터에서 시작하며, BFS를 이용하여 1번 컴퓨터와 연결되어진 다른 컴퓨터의 수를 계산
=> 바이러스 (프로그래머스 - 2606)

session1/src/week5/chaeyeon/GoSchool.java, session1/src/week5/chaeyeon/Operations.java, session1/src/week5/chaeyeon/Thief.java
➡️**알고리즘**
동적 계획법 사용
- **Case 1**: 첫 번째 집을 턴 경우 → 마지막 집은 못 턴다.
- **Case 2**: 첫 번째 집을 안 털 경우 → 마지막 집을 털 수 있다.
- 두가지ㅣ 경우로 나눠서 각각 계산하는 방식을 이용
➡️**문제풀이**
- dp1[]: 첫 번째 집을 턴 경우의 DP 배열 (n-2까지만 계산)
- dp2[]: 첫 번째 집을 털지 않은 경우의 DP 배열 (n-1까지 계산)
- Math.max(dp1[n - 2], dp2[n - 1])를 통해 두 경우 중 최대 금액을 최종 반환
=> 도둑질 (프로그래머스 - 42897)

session1/src/week5/chaeyeon/Change.java, session1/src/week5/chaeyeon/GoSchool.java, session1/src/week5/chaeyeon/Operations.java, session1/src/week5/chaeyeon/Thief.java
➡️**알고리즘**
동적 계획법 사용
➡️**문제풀이**
- `dp[0] = 1`로 설정
→ 금액 0원을 만드는 방법은 아무 동전도 사용하지 않는 1가지 방법이므로 이를 초기값으로 설정
- 동전 하나씩을 기준으로 dp 배열을 업데이트
→ 각 동전마다 가능한 금액을 순회하며 경우의 수를 누적함으로써 같은 조합이 중복되지 않도록 처리
→ 즉, 동전의 순서를 고려하지 않는 조합 방식으로 문제를 해결할 수 있다.
=> 거스름돈 (프로그래머스 - 12907)

session1/src/week5/chaeyeon/Change.java, session1/src/week5/chaeyeon/Thief.java, session1/src/week5/chaeyeon/WithTaxiFare.java
➡️**알고리즘**
플로이드-워셜 알고리즘을 이용한 동적 계획법 사용
➡️**문제풀이**
- 한 지점 s에서 두 사람(a, b)이 같이 출발해서 중간까지 합승한 뒤, 각자의 목적지까지 가는 최소 요금을 계산하는 것
- 이때 모든 지점 간의 최소 비용을 미리 알아야 하므로, 플로이드-워셜 알고리즘을 통해 모든 정점 간 최단 경로를 구했다.
- 이후, 합승을 같이 할 수 있는 모든 지점 k에 대해 s → k → a, s → k → b의 요금 합을 계산해 그 중 최소값을 반환‼️
=> 합승택시요금 (프로그래머스 - 72413)

session1/src/week5/chaeyeon/BuyCard.java, session1/src/week5/chaeyeon/Change.java, session1/src/week5/chaeyeon/Thief.java, session1/src/week5/chaeyeon/WithTaxiFare.java
➡️**알고리즘**
bottom-up 방식의 동적계획법 사용
➡️**문제풀이**
- dp[i]를 i개의 카드를 구매할 때 얻을 수 있는 최대 금액이라고 정의
- i개의 카드를 만들기 위해, j개짜리 카드팩을 구매하면 남은 카드는 i - j개가 된다.
- dp[i] = max(dp[i], dp[i - j] + cost[j])로 점화식을 세움
=> 카드구매하기 (백준 - 11052)

session1/src/week5/chaeyeon/BuyCard.java, session1/src/week5/chaeyeon/Change.java, session1/src/week5/chaeyeon/DeliverSugar.java, session1/src/week5/chaeyeon/Thief.java, session1/src/week5/chaeyeon/WithTaxiFare.java
➡️**알고리즘**
그리디 알고리즘으로도 간단하게 해결 가능하지만, 동적계획법을 연습하고자 DP를 이용하여 문제를 해결
➡️**문제풀이**
- dp[i]를 i kg의 설탕을 배달하기 위한 최소 봉지 수로 정의
- 점화식 : dp[i] = min(dp[i - 3] + 1, dp[i - 5] + 1);
=> 설탕 배달 (백준 - 2839)

session1/src/week5/chaeyeon/BuyCard.java, session1/src/week5/chaeyeon/Change.java, session1/src/week5/chaeyeon/DeliverSugar.java, session1/src/week5/chaeyeon/Thief.java, session1/src/week5/chaeyeon/TreeAndQuery.java, session1/src/week5/chaeyeon/WithTaxiFare.java, session1/src/week6/joochaeyeon/JoyStick.java, session1/src/week6/joochaeyeon/WorkoutClothes.java
➡️**문제풀이**
1. 여벌을 가진 학생이 잃어버린 학생을 도와줄 수 있는지 판단
2. 겹치는 학생(잃어버렸지만 여벌이 있는 경우)을 처리
- 각 잃어버린 학생 l에 대해 (l - 1) 또는 (l + 1)이 여벌 체육복을 가지고 있다면 빌려준다.
- 빌려준 경우, 해당 학생은 더 이상 여벌이 없으므로 reserveSet에서 제거하고, lostSet에서도 제거하여 체육복을 갖춘 상태로 만든다.
=> 체육복 (프로그래머스 - 42862)

session1/src/week5/chaeyeon/BuyCard.java, session1/src/week5/chaeyeon/Change.java, session1/src/week5/chaeyeon/DeliverSugar.java, session1/src/week5/chaeyeon/Thief.java, session1/src/week5/chaeyeon/TreeAndQuery.java, session1/src/week5/chaeyeon/WithTaxiFare.java, session1/src/week6/joochaeyeon/JoyStick.java, session1/src/week6/joochaeyeon/MakeBigNum.java, session1/src/week6/joochaeyeon/WorkoutClothes.java
➡️**문제풀이**
- 앞자리부터 하나씩 스택에 넣으면서, **스택의 top보다 현재 숫자가 클 경우 top을 제거**
- 이를 최대 `k`번 반복하면 가장 큰 수를 만들 수 있다.
=> 큰 수 만들기 (프로그래머스 - 42883)

session1/src/week5/chaeyeon/BuyCard.java, session1/src/week5/chaeyeon/Change.java, session1/src/week5/chaeyeon/DeliverSugar.java, session1/src/week5/chaeyeon/Thief.java, session1/src/week5/chaeyeon/TreeAndQuery.java, session1/src/week5/chaeyeon/WithTaxiFare.java, session1/src/week6/joochaeyeon/JoyStick.java, session1/src/week6/joochaeyeon/LifeBoat.java, session1/src/week6/joochaeyeon/MakeBigNum.java, session1/src/week6/joochaeyeon/WorkoutClothes.java
➡️**문제풀이**
- 가장 무거운 사람과 가장 가벼운 사람을 쌍으로 태울 수 있으면 태우고,안 되면 무거운 사람만 따로 태운다.
- 정렬 후, 투 포인터 방식 사용해서 문제를 풀었다.
=> 구명보트 (프로그래머스 - 42885)

session1/src/week5/chaeyeon/BuyCard.java, session1/src/week5/chaeyeon/Change.java, session1/src/week5/chaeyeon/DeliverSugar.java, session1/src/week5/chaeyeon/Thief.java, session1/src/week5/chaeyeon/TreeAndQuery.java, session1/src/week5/chaeyeon/WithTaxiFare.java, session1/src/week6/joochaeyeon/ConnectLand.java, session1/src/week6/joochaeyeon/JoyStick.java, session1/src/week6/joochaeyeon/LifeBoat.java, session1/src/week6/joochaeyeon/MakeBigNum.java, session1/src/week6/joochaeyeon/WorkoutClothes.java
➡️**알고리즘**
모든 정점을 연결해야 하므로, 정점 중심의 프림 알고리즘을 사용하여 최소 신장 트리를 구성
➡️**문제풀이**
- 인접 리스트로 그래프를 구성하고, 우선순위 큐를 사용해 가장 비용이 적은 간선부터 선택
- 방문하지 않은 노드만 연결하여 사이클을 방지하며, 모든 노드를 연결할 때까지 반복!
=> 섬 연결하기 (프로그래머스 - 42861)

session1/src/week5/chaeyeon/BuyCard.java, session1/src/week5/chaeyeon/Change.java, session1/src/week5/chaeyeon/DeliverSugar.java, session1/src/week5/chaeyeon/Thief.java, session1/src/week5/chaeyeon/TreeAndQuery.java, session1/src/week5/chaeyeon/WithTaxiFare.java, session1/src/week6/joochaeyeon/Camera.java, session1/src/week6/joochaeyeon/ConnectLand.java, session1/src/week6/joochaeyeon/JoyStick.java, session1/src/week6/joochaeyeon/LifeBoat.java, session1/src/week6/joochaeyeon/MakeBigNum.java, session1/src/week6/joochaeyeon/WorkoutClothes.java
➡️**문제풀이**
- 차량들의 진출 지점을 기준으로 오름차순 정렬
- 진출 지점에 설치하는 이유는 가능한 한 뒤쪽에 설치하여 이후 차량들과 겹치는 구간을 최대한 커버하기 위함이다‼️
- 기존 카메라가 해당 차량의 구간을 커버하지 못하면, 해당 차량의 진출 지점에 카메라를 새로 설치
=> 단속 카메라 (프로그래머스 - 42884)

session1/src/week5/chaeyeon/BuyCard.java, session1/src/week5/chaeyeon/Change.java, session1/src/week5/chaeyeon/DeliverSugar.java, session1/src/week5/chaeyeon/Thief.java, session1/src/week5/chaeyeon/TreeAndQuery.java, session1/src/week5/chaeyeon/WithTaxiFare.java, session1/src/week6/joochaeyeon/JoyStick.java
➡️**문제풀이**
- `Math.min(c - 'A', 'Z' - c + 1)` : 알파벳 상하 조작 최소값
- `minMove = len - 1` : 기본적으로 오른쪽으로 쭉 가는 경우
- `i * 2 + len - next`  : 앞에서 처리 후 돌아와서 뒤쪽 처리, 앞->뒤, 뒤->앞이기에 i*2처리
- `i + (len - next) * 2` : 뒤에서 처리 후 돌아와서 앞쪽 처리
=> 조이스틱 (프로그래머스 - 42860)

session2/week1/chaeyeon/Corner.java, session2/week1/chaeyeon/Marry.java, session2/week1/chaeyeon/MinimumCost.java
➡️**알고리즘**
- a→b 로 가는데 드는 최소비용구하는 문제이며 음의 간선이 존재하지 않기에 다익스트라 알고리즘 사용
➡️**문제풀이**
- 전형적인 다익스트라 알고리즘 문제
=> 최소비용 구하기 (백준 - 1916)

session2/week1/chaeyeon/Corner.java, session2/week1/chaeyeon/Marry.java
➡️**알고리즘**
BFS 활용
➡️**문제풀이**
- 해당 문제의 포인트는 결국 1번의 친구 + 1번의 친구의 친구까지를 BFS로 탐색하는 것인데
- 이 말은 즉 BFS탐색을 depth 2까지만 하면 된다는 것을 의미‼️
=> 결혼식 (백준 - 5567)

session2/week1/chaeyeon/LimitWeight.java
➡️**알고리즘**
간선의 양의 가중치가 존재하기에 다익스트라 알고리즘 사용 
➡️**문제풀이**
전형적인 다익스트라 알고리즘 문제
=> 중량제한 (백준 - 1939)

session2/week1/chaeyeon/LimitWeight.java, session2/week2/chaeyeon/Operation.java
➡️**알고리즘**
백트래킹
➡️**문제풀이**
- 재귀 호출 시마다 사용할 수 있는 연산자를 하나씩 선택해 현재까지 계산된 값에 적용
- 연산자 개수를 감소시켰다가 재귀 종료 후 다시 복구하는 방식을 사용하여 모든 조합을 완전 탐색
=> 연산자 끼워넣기 (백준 - 14888)

session2/week2/chaeyeon/Abcde.java, session2/week2/chaeyeon/Operation.java
➡️**알고리즘**
DFS를 활용한 백트래킹 사용
➡️**문제풀이**
- 문제의 핵심은 친구 관계가 5명까지 이어졌으면 조건을 만족한다는 것!
- 따라서 dfs 를 활용한 백트래킹 알고리즘을 활용해서 해당 조건을 만족하는 지를 확인
=> abcde (백준 - 13023)

session2/week2/chaeyeon/SwitchBall.java
=> 공 바꾸기 (백준 - 10813)

session1/src/week5/gayeong/Exchange.java
> dp[i] = i원을 만들 수 있는 방법의 수
dp[i] += dp[i - coin]
=> 거스름돈 문제 풀이

session2/week2/chaeyeon/bfsdfs/Marry1.java
https://www.acmicpc.net/problem/5567
- bfs 알고리즘을 사용
- 2606 번과 동일한 문제풀이 사용
=> feat : bfs-백준 5567번
